"use client";

import React, { useState } from "react";
import styles from "./faq.module.css";

const FAQItem = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className={styles.faqItem}>
      <div
        className={`${styles.faqQuestion} ${isOpen ? styles.active : ""}`}
        onClick={() => setIsOpen(!isOpen)}
      >
        <span className={styles.faqQuestionText}>{question}</span>
        <span className={styles.faqQuestionIcon}>▼</span>
      </div>
      <div className={`${styles.faqAnswer} ${isOpen ? styles.show : ""}`}>
        {answer}
      </div>
    </div>
  );
};

export default function FAQ() {
  const faqData = [
    {
      question: "What is WebSim?",
      answer:
        "WebSim is an innovative platform that allows users to explore and create simulated websites within an imaginary internet. It's a playground for web design, alternate realities, and creative storytelling through hypertext.",
    },
    {
      question: "How does WebSim work?",
      answer:
        "WebSim uses advanced AI to generate realistic web pages based on user input. You can navigate this simulated web by clicking on links, entering URLs, or using search functions, just like you would on the real internet. The AI dynamically creates content, maintaining consistency within the simulated world.",
    },
    {
      question: "Can I create my own websites on WebSim?",
      answer:
        "Absolutely! WebSim encourages users to contribute to the simulated internet. You can create your own websites by providing a URL and description. The AI will then generate a full webpage based on your input, which becomes part of the broader WebSim ecosystem.",
    },
    {
      question: "Is WebSim connected to the real internet?",
      answer:
        "No, WebSim is an entirely separate, simulated internet. While it may reference real-world concepts, all websites and content within WebSim are fictional and generated by AI. It's a safe space for exploration and creativity without real-world consequences.",
    },
    {
      question: "How can I get started with WebSim?",
      answer:
        "To get started, simply visit our homepage at websim.ai and start browsing! You can enter any URL you can imagine into the address bar, or click on suggested links. To create your own sites, sign up for a free account and use our intuitive site creation tools.",
    },
  ];

  return (
    <div className={styles.faqContainer}>
      <h1 className={styles.title}>FAQ</h1>
      <div className={styles.faqContainer}>
        {faqData.map((item, index) => (
          <FAQItem key={index} question={item.question} answer={item.answer} />
        ))}
      </div>
    </div>
  );
}
